return {
	mod_name = {
		en = "Auto Ping",
		de = "Auto-Markierung",
		fr = "Marquage Automatique",
		ru = "Авто-Тег",
		["zh-cn"] = "自动标记",
	},
	mod_description = {
		en = "DOGGY UPDATE",
		de = "Markiert automatisch Feinde im Fadenkreuz, mit einer internen Abklingzeit, um Spam zu verhindern.\nDie Abklingzeit wird zurückgesetzt, wenn der markierte Feind stirbt.\nEnthält jetzt Feind-Filterung und Prioritäts-Zielen.",
		fr = "Marque automatiquement les ennemis dans le réticule, avec un temps de recharge interne pour éviter le spam.\nLe temps de recharge se réinitialise lorsque l'ennemi marqué meurt.\nInclut maintenant le filtrage des ennemis et le ciblage prioritaire.",
		ru = "Автоматически помечает врагов в прицеле, с внутренним кулдауном, чтобы предотвратить спам.\nКулдаун обновляется, когда помеченный враг умирает.\nТеперь включает фильтрацию врагов и приоритетное нацеливание.",
		["zh-cn"] = "自动标记准星中的敌人，并设置内部冷却以防止滥用。\n当标记的敌人死亡时，冷却刷新。\n现在包括敌人过滤和优先目标。",
	},
	cd = {
		en = "Cooldown (Seconds)",
		de = "Abklingzeit (Sekunden)",
		fr = "Temps de recharge (Secondes)",
		ru = "Перезарядка (Секунды)",
		["zh-cn"] = "冷却时间（秒）",
	},
	manualoverride = {
		en = "Override Manual Tag",
		de = "Manuelles Taggen überschreiben",
		fr = "Remplacer le marquage manuel",
		ru = "Принудительное ручное помечание",
		["zh-cn"] = "覆盖手动标记",
	},
	refresh = {
		en = "Refresh Cooldown",
		de = "Abklingzeit erneuern",
		fr = "Rafraîchir le temps de recharge",
		ru = "Обновить кулдаун",
		["zh-cn"] = "刷新冷却",
	},
	refresh_description = {
		en = "Refreshes tag cooldown when tag expires or your tagged target dies.",
		de = "Erneuert die Markierungs-Abklingzeit, wenn die Markierung abläuft oder das markierte Ziel stirbt.",
		fr = "Rafraîchit le temps de recharge du marquage lorsque le marquage expire ou que votre cible marquée meurt.",
		ru = "Обновляет кулдаун метки, когда метка истекает или помеченная цель умирает.",
		["zh-cn"] = "当标记过期或标记目标死亡时刷新标记冷却。",
	},
	filter_mode = {
		en = "Enemy Filter Mode",
		de = "Feind-Filtermodus",
		fr = "Mode de filtrage des ennemis",
		ru = "Режим фильтрации врагов",
		["zh-cn"] = "敌人过滤模式",
	},
	filter_mode_all_pingable = {
		en = "All Pingable Enemies",
		de = "Alle markierbaren Feinde",
		fr = "Tous les ennemis marquables",
		ru = "Все помечаемые враги",
		["zh-cn"] = "所有可标记敌人",
	},
	filter_mode_high_priority = {
		en = "High Priority Only",
		de = "Nur hohe Priorität",
		fr = "Haute priorité uniquement",
		ru = "Только высокий приоритет",
		["zh-cn"] = "仅高优先级",
	},
	filter_mode_specials_elites = {
		en = "Specials + Elites",
		de = "Spezialeinheiten + Eliten",
		fr = "Spéciaux + Élites",
		ru = "Специальные + Элитные",
		["zh-cn"] = "特殊+精英",
	},
	filter_mode_custom = {
		en = "Custom Filter",
		de = "Benutzerdefinierter Filter",
		fr = "Filtre personnalisé",
		ru = "Пользовательский фильтр",
		["zh-cn"] = "自定义过滤器",
	},
	priority_targeting = {
		en = "Priority Targeting",
		de = "Prioritäts-Zielen",
		fr = "Ciblage prioritaire",
		ru = "Приоритетное нацеливание",
		["zh-cn"] = "优先目标",
	},
	priority_targeting_description = {
		en = "Switch to higher priority targets automatically. Bosses > High Priority > Medium Priority.",
		de = "Wechselt automatisch zu höheren Prioritätszielen. Bosse > Hohe Priorität > Mittlere Priorität.",
		fr = "Bascule automatiquement vers les cibles de priorité plus élevée. Boss > Haute priorité > Priorité moyenne.",
		ru = "Автоматически переключается на цели с более высоким приоритетом. Боссы > Высокий приоритет > Средний приоритет.",
		["zh-cn"] = "自动切换到更高优先级目标。首领 > 高优先级 > 中等优先级。",
	},
	companion_attack_mode = {
		en = "Companion Attack Commands",
		de = "Begleiter-Angriffsbefehle",
		fr = "Commandes d'attaque du compagnon",
		ru = "Команды атаки компаньона",
		["zh-cn"] = "同伴攻击命令",
	},
	companion_attack_mode_description = {
		en = "Double-press ping to send companion attack commands to targeted enemies.",
		de = "Doppelklick auf Markierung, um Begleiter-Angriffsbefehle an markierte Feinde zu senden.",
		fr = "Double-clic sur le marquage pour envoyer des commandes d'attaque du compagnon aux ennemis ciblés.",
		ru = "Двойной клик по метке для отправки команд атаки компаньона на помеченных врагов.",
		["zh-cn"] = "双击标记向目标敌人发送同伴攻击命令。",
	},
	debug_mode = {
		en = "Debug Mode",
		de = "Debug-Modus",
		fr = "Mode débogage",
		ru = "Режим отладки",
		["zh-cn"] = "调试模式",
	},
	debug_mode_description = {
		en = "Shows tagged enemy names in chat for debugging.",
		de = "Zeigt markierte Feindnamen im Chat für Debugging.",
		fr = "Affiche les noms des ennemis marqués dans le chat pour le débogage.",
		ru = "Показывает имена помеченных врагов в чате для отладки.",
		["zh-cn"] = "在聊天中显示标记的敌人名称以进行调试。",
	},
	-- Priority level options
	priority_settings_header = {
		en = "Enemy Priority Settings",
		de = "Feind-Prioritäts-Einstellungen",
		fr = "Paramètres de priorité des ennemis",
		ru = "Настройки приоритета врагов",
		["zh-cn"] = "敌人优先级设置",
	},
	priority_high = {
		en = "High Priority",
		de = "Hohe Priorität",
		fr = "Haute priorité",
		ru = "Высокий приоритет",
		["zh-cn"] = "高优先级",
	},
	priority_medium = {
		en = "Medium Priority",
		de = "Mittlere Priorität",
		fr = "Priorité moyenne",
		ru = "Средний приоритет",
		["zh-cn"] = "中等优先级",
	},
	priority_disabled = {
		en = "Disabled",
		de = "Deaktiviert",
		fr = "Désactivé",
		ru = "Отключено",
		["zh-cn"] = "禁用",
	},
	-- Boss enemy priority settings (NEW)
	priority_chaos_beast_of_nurgle = {
		en = "Beast of Nurgle Priority",
		de = "Bestie von Nurgle Priorität",
		fr = "Priorité Bête de Nurgle",
		ru = "Приоритет Зверь Нургла",
		["zh-cn"] = "纳垢之兽优先级",
	},
	priority_chaos_plague_ogryn = {
		en = "Plague Ogryn Priority",
		de = "Pest-Ogryn Priorität",
		fr = "Priorité Ogryn pestiféré",
		ru = "Приоритет Чумной огрин",
		["zh-cn"] = "瘟疫食人魔优先级",
	},
	priority_chaos_daemonhost = {
		en = "Daemonhost Priority",
		de = "Dämonenwirt Priorität",
		fr = "Priorité Hôte démoniaque",
		ru = "Приоритет Демонхост",
		["zh-cn"] = "恶魔宿主优先级",
	},
	priority_chaos_spawn = {
		en = "Chaos Spawn Priority",
		de = "Chaos-Brut Priorität",
		fr = "Priorité Rejeton du chaos",
		ru = "Приоритет Порождение хаоса",
		["zh-cn"] = "混沌孽种优先级",
	},
	-- High Priority Enemies (Specials/Disablers)
	priority_cultist_flamer = {
		en = "Green Flamer Priority",
		de = "Kultist-Flammenwerfer Priorität",
		fr = "Priorité Lanceur de flammes cultiste",
		ru = "Приоритет Культист-огнеметчик",
		["zh-cn"] = "邪教火焰兵优先级",
	},
	priority_renegade_berzerker = {
		en = "Armored Rager Priority",
		de = "Gepanzerter Rasender Priorität",
		fr = "Priorité Enragé blindé",
		ru = "Приоритет Бронированный берсерк",
		["zh-cn"] = "装甲狂怒者优先级",
	},
	priority_renegade_flamer = {
		en = "Red Flamer Priority",
		de = "Roter Flammenwerfer Priorität",
		fr = "Priorité Lanceur de flammes rouge",
		ru = "Приоритет Красный огнеметчик",
		["zh-cn"] = "红色火焰兵优先级",
	},
	priority_cultist_berzerker = {
		en = "Naked Rager Priority",
		de = "Nackter Rasender Priorität",
		fr = "Priorité Enragé nu",
		ru = "Приоритет Голый берсерк",
		["zh-cn"] = "裸体狂怒者优先级",
	},
	priority_renegade_netgunner = {
		en = "Trapper Priority",
		de = "Fallensteller Priorität",
		fr = "Priorité Piégeur",
		ru = "Приоритет Ловушечник",
		["zh-cn"] = "陷阱手优先级",
	},
	priority_renegade_sniper = {
		en = "Sniper Priority",
		de = "Scharfschütze Priorität",
		fr = "Priorité Tireur d'élite",
		ru = "Приоритет Снайпер",
		["zh-cn"] = "狙击手优先级",
	},
	priority_cultist_grenadier = {
		en = "Gas Grenadier Priority",
		de = "Gas-Grenadier Priorität",
		fr = "Priorité Grenadier à gaz",
		ru = "Приоритет Газовый гренадер",
		["zh-cn"] = "毒气榴弹兵优先级",
	},
	priority_renegade_grenadier = {
		en = "Flame Grenadier Priority",
		de = "Flammen-Grenadier Priorität",
		fr = "Priorité Grenadier incendiaire",
		ru = "Приоритет Огненный гренадер",
		["zh-cn"] = "火焰榴弹兵优先级",
	},
	priority_chaos_hound = {
		en = "Hound Priority",
		de = "Hund Priorität",
		fr = "Priorité Chien",
		ru = "Приоритет Пес",
		["zh-cn"] = "猎犬优先级",
	},
	priority_chaos_poxwalker_bomber = {
		en = "Poxburster Bomber Priority",
		de = "Poxplatzer-Bomber Priorität",
		fr = "Priorité Bombardier poxplatzer",
		ru = "Приоритет Поксвзрыватель",
		["zh-cn"] = "毒疮爆破兵优先级",
	},
	-- Medium Priority Enemies (Elites)
	priority_renegade_gunner = {
		en = "Laz Gunner Priority",
		de = "Laz-Schütze Priorität",
		fr = "Priorité Artilleur Laz",
		ru = "Приоритет Лаз-пулеметчик",
		["zh-cn"] = "拉兹机枪手优先级",
	},
	priority_cultist_gunner = {
		en = "Gunner Priority",
		de = "Schütze Priorität",
		fr = "Priorité Artilleur",
		ru = "Приоритет Пулеметчик",
		["zh-cn"] = "机枪手优先级",
	},
	priority_renegade_shocktrooper = {
		en = "Dreg Shotgunner Priority",
		de = "Dreg-Schrotschütze Priorität",
		fr = "Priorité Fusil à pompe Dreg",
		ru = "Приоритет Дрег-дробовик",
		["zh-cn"] = "渣滓霰弹手优先级",
	},
	priority_cultist_shocktrooper = {
		en = "Scab Shotgunner Priority",
		de = "Scab-Schrotschütze Priorität",
		fr = "Priorité Fusil à pompe Scab",
		ru = "Приоритет Скаб-дробовик",
		["zh-cn"] = "疥疮霰弹手优先级",
	},
	priority_chaos_ogryn_executor = {
		en = "Chaos Ogryn Executor Priority",
		de = "Chaos-Ogryn-Henker Priorität",
		fr = "Priorité Exécuteur Ogryn du chaos",
		ru = "Приоритет Хаос-огрин-палач",
		["zh-cn"] = "混沌食人魔刽子手优先级",
	},
	priority_chaos_ogryn_gunner = {
		en = "Chaos Ogryn Gunner Priority",
		de = "Chaos-Ogryn-Schütze Priorität",
		fr = "Priorité Artilleur Ogryn du chaos",
		ru = "Приоритет Хаос-огрин-пулеметчик",
		["zh-cn"] = "混沌食人魔机枪手优先级",
	},
	priority_chaos_ogryn_bulwark = {
		en = "Ogryn Bulwark Priority",
		de = "Ogryn-Bollwerk Priorität",
		fr = "Priorité Rempart Ogryn",
		ru = "Приоритет Огрин-бастион",
		["zh-cn"] = "食人魔壁垒优先级",
	},
	priority_renegade_executor = {
		en = "Mauler Priority",
		de = "Schläger Priorität",
		fr = "Priorité Matraqueur",
		ru = "Приоритет Молотобоец",
		["zh-cn"] = "重锤手优先级",
	},
	priority_cultist_mutant = {
		en = "Mutant Priority",
		de = "Mutant Priorität",
		fr = "Priorité Mutant",
		ru = "Приоритет Мутант",
		["zh-cn"] = "变异体优先级",
	},
	-- Individual enemy type settings (Legacy custom mode)
	tag_cultist_flamer = {
		en = "Green Flamer",
		de = "Grüner Flammenwerfer",
		fr = "Lanceur de flammes vert",
		ru = "Зеленый огнеметчик",
		["zh-cn"] = "绿色火焰兵",
	},
	tag_renegade_flamer = {
		en = "Red Flamer",
		de = "Roter Flammenwerfer",
		fr = "Lanceur de flammes rouge",
		ru = "Красный огнеметчик",
		["zh-cn"] = "红色火焰兵",
	},
	tag_renegade_netgunner = {
		en = "Trapper",
		de = "Fallensteller",
		fr = "Piégeur",
		ru = "Ловушечник",
		["zh-cn"] = "陷阱手",
	},
	tag_renegade_sniper = {
		en = "Sniper",
		de = "Scharfschütze",
		fr = "Tireur d'élite",
		ru = "Снайпер",
		["zh-cn"] = "狙击手",
	},
	tag_cultist_grenadier = {
		en = "Gas Grenadier",
		de = "Gas-Grenadier",
		fr = "Grenadier à gaz",
		ru = "Газовый гренадер",
		["zh-cn"] = "毒气榴弹兵",
	},
	tag_renegade_grenadier = {
		en = "Fire Grenadier",
		de = "Feuer-Grenadier",
		fr = "Grenadier incendiaire",
		ru = "Огненный гренадер",
		["zh-cn"] = "火焰榴弹兵",
	},
	tag_renegade_gunner = {
		en = "Laz Gunner",
		de = "Laz-Schütze",
		fr = "Artilleur Laz",
		ru = "Лаз-пулеметчик",
		["zh-cn"] = "拉兹机枪手",
	},
	tag_cultist_gunner = {
		en = "Gunner",
		de = "Schütze",
		fr = "Artilleur",
		ru = "Пулеметчик",
		["zh-cn"] = "机枪手",
	},
	tag_renegade_shocktrooper = {
		en = "Scab Shocktrooper",
		de = "Scab-Sturmsoldat",
		fr = "Soldat d'assaut Scab",
		ru = "Скаб-штурмовик",
		["zh-cn"] = "疥疮突击兵",
	},
	tag_cultist_shocktrooper = {
		en = "Dreg Shocktrooper",
		de = "Dreg-Sturmsoldat",
		fr = "Soldat d'assaut Dreg",
		ru = "Дрег-штурмовик",
		["zh-cn"] = "渣滓突击兵",
	},
	tag_chaos_hound = {
		en = "Chaos Hound",
		de = "Chaos-Hund",
		fr = "Chien du chaos",
		ru = "Хаос-пес",
		["zh-cn"] = "混沌猎犬",
	},
	tag_chaos_ogryn_executor = {
		en = "Crusher",
		de = "Zermalmer",
		fr = "Broyeur",
		ru = "Дробитель",
		["zh-cn"] = "破碎者",
	},
	tag_chaos_ogryn_gunner = {
		en = "Reaper",
		de = "Schnitter",
		fr = "Faucheur",
		ru = "Жнец",
		["zh-cn"] = "收割者",
	},
	tag_chaos_poxwalker_bomber = {
		en = "PoxBomber",
		de = "Poxbomber",
		fr = "Bombardier pox",
		ru = "Поксбомбер",
		["zh-cn"] = "毒疮爆破兵",
	},
	tag_chaos_ogryn_bulwark = {
		en = "Bulwark",
		de = "Bollwerk",
		fr = "Rempart",
		ru = "Бастион",
		["zh-cn"] = "壁垒",
	},
	tag_renegade_executor = {
		en = "Mauler",
		de = "Schläger",
		fr = "Matraqueur",
		ru = "Молотобоец",
		["zh-cn"] = "重锤手",
	},
	tag_chaos_spawn = {
		en = "Chaos Spawn",
		de = "Chaos-Brut",
		fr = "Rejeton du chaos",
		ru = "Порождение хаоса",
		["zh-cn"] = "混沌孽种",
	},
	tag_cultist_mutant = {
		en = "Mutant",
		de = "Mutant",
		fr = "Mutant",
		ru = "Мутант",
		["zh-cn"] = "变异体",
	},
	tag_cultist_berzerker = {
		en = "Naked Rager",
		de = "Nackter Rasender",
		fr = "Enragé nu",
		ru = "Голый берсерк",
		["zh-cn"] = "裸体狂怒者",
	},
	tag_renegade_berzerker = {
		en = "Armored Rager",
		de = "Gepanzerter Rasender",
		fr = "Enragé blindé",
		ru = "Бронированный берсерк",
		["zh-cn"] = "装甲狂怒者",
	},
	-- Boss enemies for custom mode (NEW)
	tag_chaos_beast_of_nurgle = {
		en = "Beast of Nurgle",
		de = "Bestie von Nurgle",
		fr = "Bête de Nurgle",
		ru = "Зверь Нургла",
		["zh-cn"] = "纳垢之兽",
	},
	tag_chaos_plague_ogryn = {
		en = "Plague Ogryn",
		de = "Pest-Ogryn",
		fr = "Ogryn pestiféré",
		ru = "Чумной огрин",
		["zh-cn"] = "瘟疫食人魔",
	},
	tag_chaos_daemonhost = {
		en = "Daemonhost",
		de = "Dämonenwirt",
		fr = "Hôte démoniaque",
		ru = "Демонхост",
		["zh-cn"] = "恶魔宿主",
	}
}